baseURL = 'https://Njorda.github.io'
languageCode = 'en-us'
title = 'Njord tech blog'
theme = 'theme="archie'

[params]
  SEOTitle = "Niklas Hansson, Johan Hansson | Njord Tech blog"
  description = "Data, distributed systems and software engineering"
  slogan = "One commit a day, keeps the slides away"

  about_me = true

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"
